<?php
declare(strict_types=1);
function current_user():?array{return $_SESSION['user']??null;}
function is_logged_in():bool{return isset($_SESSION['user']);}
function current_role():?string{return $_SESSION['user']['role']??null;}
function require_login():void{if(!is_logged_in()){set_flash('error','Please log in to continue.');redirect('login.php');}}
function register_user(PDO $pdo,array $d):array{$name=clean_input($d['full_name']??'');$email=strtolower(trim($d['email']??''));$pass=$d['password']??'';$role=($d['role']??'customer')==='sme'?'sme':'customer';$phone=clean_input($d['phone']??'');$district=clean_input($d['district']??'');$business=clean_input($d['business_name']??'');if(!$name||!is_valid_email($email)||!is_valid_password($pass))return['success'=>false,'error'=>'Enter a valid name, email and password (8+ characters with a letter and number).'];$s=$pdo->prepare('SELECT id FROM users WHERE email=?');$s->execute([$email]);if($s->fetch())return['success'=>false,'error'=>'An account with this email already exists.'];try{$pdo->beginTransaction();$s=$pdo->prepare('INSERT INTO users(full_name,email,password_hash,role,phone,district) VALUES(?,?,?,?,?,?)');$s->execute([$name,$email,password_hash($pass,PASSWORD_DEFAULT),$role,$phone,$district]);$uid=(int)$pdo->lastInsertId();if($role==='sme'){$s=$pdo->prepare('INSERT INTO smes(user_id,business_name,district,business_phone) VALUES(?,?,?,?)');$s->execute([$uid,$business,$district,$phone]);}$pdo->commit();return['success'=>true,'error'=>null];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();return['success'=>false,'error'=>DEV_MODE?$e->getMessage():'Registration failed.'];}}
function login_user(PDO $pdo,string $email,string $password):array{$s=$pdo->prepare('SELECT * FROM users WHERE email=? AND status="active"');$s->execute([strtolower(trim($email))]);$u=$s->fetch();if(!$u||!password_verify($password,$u['password_hash']))return['success'=>false,'error'=>'Incorrect email or password.'];session_regenerate_id(true);$_SESSION['user']=['id'=>(int)$u['id'],'full_name'=>$u['full_name'],'email'=>$u['email'],'role'=>$u['role']];if($u['role']==='sme'){$s=$pdo->prepare('SELECT id FROM smes WHERE user_id=?');$s->execute([$u['id']]);$_SESSION['user']['sme_id']=(int)($s->fetchColumn()?:0);}return['success'=>true,'error'=>null];}
function logout_user():void{$_SESSION=[];if(ini_get('session.use_cookies')){ $p=session_get_cookie_params();setcookie(session_name(),' ',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();}
